### ISSUE TITLE
Portal site map

### ISSUE THREAD

**Issue by bogdangi** [AGcompany/AG.Places#10]
Hi Pavel,

Could you please prepare site map?

Best regards,
Bogdan.

**Comment by PavelAvramidi** [comment]
Hi Bogdan,
- Homepage
- News
- Events
- Accommodation
- Traveling
- Tourism
- Weather
- Transport
- Profile
- Search

Please review this site map and leave your feedback
BR,
Pavel

**Comment by bogdangi** [comment]
Hi Pavel,

It looks good.
You can add this to portal.

Best regards,
Bogdan.

**Comment by PavelAvramidi** [comment]
Done
