### ISSUE TITLE
Portal layout

### ISSUE THREAD

**Issue by bogdangi** [AGcompany/AG.Places#9]
Hi Pavel,

Could you please prepare layout for portal.

Best regards,
Bogdan.

**Comment by PavelAvramidi** [comment]
Hi Bogdan,

Please review next layout:
http://plone.org/products/plonetheme.discovery

Br,
Pavel

**Comment by bogdangi** [comment]
Hi Pavel,

I've prepared new package https://github.com/AGcompany/AG.krymgid.policy for krymgid.com portal.
This package helps to us implement features depend for current portal.
I've included plonetheme.discovery theme, it looks good.

Best regards,
Bogdan.

**Comment by bogdangi** [comment]
Added package for portal theme https://github.com/AGcompany/AG.krymgid.theme
